version: "2"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/usr/share/nginx/html
    command: npm run start
